# Generated by Django 5.2 on 2025-05-09 11:33

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=django_summernote.fields.SummernoteTextField(max_length=10000),
        ),
    ]
